language: scala

jdk:
  - oraclejdk7

addons:
  apt:
    sources:
      r-packages-precise
    packages:
      r-base

script:
  - mvn verify -Dtest.redirectToFile=false

before_install:
  - wget $MVN_SETTINGS_URL -O $HOME/.m2/settings.xml
  - pip install --user codecov

after_success:
  - codecov
